// List of jobs here with .map from database

export const metadata = {
    title: "Job Board | The Outpost",
    description: "Generated by create next app",
  };


export default function Jobboard() {

    return (
        <>
        <h1>List of jobs go here with .map from database</h1>
        </>
    )
}