// All jobs that are created via the newjobform are displayed here //
import Link from "next/link";
import "../styles/jobboard.css";
import { db } from "@/lib/db";

// Metadata for browser page title //
export const metadata = {
  title: "Job Board | The Outpost",
  description: "Generated by create next app",
};

// Main function for mapping through jobs table and displaying them on the page. //
export default async function Jobboard() {
  const jobs = await db.query(
    `SELECT jobs.title, users.name, jobs.id, difficulty.type FROM jobs
      JOIN users ON jobs.user_id = users.id
      JOIN difficulty ON jobs.difficulty_id = difficulty.id`
  );
  // console.log(jobs.rows);

  return (
    <>
      <nav className="jobCardArea">
        {jobs.rows.map((jobs) => {
          return (
            <Link href={`/jobboard/${jobs.id}`} key={jobs.title + jobs.id}>
              <div key={jobs.title} className="jobCard">
                <h2>{jobs.title}</h2>
                <p>{jobs.name}</p>
                <p>Difficulty: {jobs.type}</p>
              </div>
            </Link>
          );
        })}
      </nav>
    </>
  );
}
