// Saved Jobs go here when accepted from the main job board //

export const metadata = {
    title: "Saved Jobs | The Outpost",
    description: "Generated by create next app",
  };

export default function SavedJobs() {

    return (
        <>
        <h1>Saved jobs go here</h1>

        </>
    )
}