// Saved Jobs PAGE //
// All Saved Jobs are displayed here when accepted from the main job board //
import Link from "next/link";
import { db } from "@/lib/db";
import "../styles/jobboard.css";

export const metadata = {
  title: "Saved Jobs | The Outpost",
  description: "Generated by create next app",
};

export default async function SavedJobs() {
  const savedJobs =
    await db.query(`SELECT saved.title, users.name, saved.id, difficulty.type FROM saved
  JOIN users ON saved.user_id = users.id
  JOIN difficulty ON saved.difficulty_id = difficulty.id`);

  return (
    <>
      <nav className="jobCardArea">
        {savedJobs.rows.map((savedJobs) => {
          return (
            <Link
              href={`/savedjobs/${savedJobs.id}`}
              key={savedJobs.title + savedJobs.id}
            >
              <div key={savedJobs.title} className="jobCard">
                <h2>{savedJobs.title}</h2>
                <p>{savedJobs.name}</p>
                <p>Difficulty: {savedJobs.type}</p>
              </div>
            </Link>
          );
        })}
      </nav>
    </>
  );
}
